spring.application.name=backend

# TEMPORAIRE : on désactive l'auto-config de la base de données
# tant qu'on n'a pas encore installé PostgreSQL
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

